gestion_cantine:
    resource: "@GestionCantineBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /admin/message